#  docker componse version
version: '3.2'

# services to run (diff containers required)
services:
    postgres-service:
      image: postgres 
      ports: 
        -  '5432:5432'
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: review
        POSTGRES_PASSWORD: password

    redis-service:
       image: redis
       ports:
        - "6500:6379"